<?php

// This array defines the games and their ratings, etc.
$gamesLucas = array(
	'Grim Fandango'                                         => array('grim','30'),
	'Grim Fandango Demo'                                    => array('grimdemo',' 5'),
	'Escape from Monkey Island'                             => array('monkey',' 0'),
	'Escape from Monkey Island Demo'                        => array('monkeydemo',' 0'),
	);

$gamesCompanies = array(
"LucasArts"                  => $gamesLucas,
	);

$notes = array(
"grim"		=> "Game is partialy playable.",
"grimdemo"	=> "Game does not start.",
"monkey"	=> "Not supported.",
"monkeydemo"	=> "Not supported.",
);

?>
